openapi: "3.0.0"
info:
  version: 1.0.0
  title: NVA Swagger main page
  description: Some documentation that applies to all internal endpoints. Some documentation that applies to all internal endpoints. Some documentation that applies to all internal endpoints. Some documentation that applies to all internal endpoints.
  license:
    name: MIT
servers:
  - url: https://example.com/
