openapi: "3.0.0"
info:
  version: 1.0.0
  title: NVA Swagger main page
  description: Some documentation that applies to all endpoints. Some documentation that applies to all endpoints. Some documentation that applies to all endpoints. Some documentation that applies to all endpoints.
  license:
    name: MIT
servers:
  - url: https://example.com/
